"""alert_events_and_device_configs

Revision ID: 958308305136
Revises: ebb4657960fd
Create Date: 2026-06-12 12:15:54.407535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958308305136'
down_revision: Union[str, None] = 'ebb4657960fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reading_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_device_id'), 'alert_events', ['device_id'], unique=False)
    op.create_table('device_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('temperature_c_max', sa.Float(), nullable=True),
    sa.Column('temperature_c_min', sa.Float(), nullable=True),
    sa.Column('co2_ppm_max', sa.Float(), nullable=True),
    sa.Column('humidity_pct_min', sa.Float(), nullable=True),
    sa.Column('humidity_pct_max', sa.Float(), nullable=True),
    sa.Column('ph_min', sa.Float(), nullable=True),
    sa.Column('ph_max', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_configs_device_id'), 'device_configs', ['device_id'], unique=True)
    op.alter_column('devices', 'device_secret_enc',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('sensor_readings_time_idx', table_name='sensor_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sensor_readings_time_idx', 'sensor_readings', [sa.text('time DESC')], unique=False)
    op.alter_column('devices', 'device_secret_enc',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.drop_index(op.f('ix_device_configs_device_id'), table_name='device_configs')
    op.drop_table('device_configs')
    op.drop_index(op.f('ix_alert_events_device_id'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
