"""Add compost item cache

Revision ID: 95528b16e7e2
Revises: abcdef123456
Create Date: 2026-06-29 00:00:49.641772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95528b16e7e2'
down_revision: Union[str, None] = 'abcdef123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compost_item_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('compostable', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('tips', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compost_item_cache_item_name'), 'compost_item_cache', ['item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compost_item_cache_item_name'), table_name='compost_item_cache')
    op.drop_table('compost_item_cache')
    # ### end Alembic commands ###
