"""add_onboarding_fields

Revision ID: 1398f2d1eeff
Revises: d2e6f6c9bfab
Create Date: 2026-06-29 20:07:39.613870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1398f2d1eeff'
down_revision: Union[str, None] = 'd2e6f6c9bfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('placement', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('diet_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('non_veg_frequency', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'non_veg_frequency')
    op.drop_column('users', 'diet_type')
    op.drop_column('users', 'placement')
    # ### end Alembic commands ###
