"""Add MarketplaceOffer

Revision ID: d731abc0ae74
Revises: 095e64076428
Create Date: 2026-07-20 12:53:25.346514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd731abc0ae74'
down_revision: Union[str, None] = '095e64076428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_phone', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('vendor_type', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('compost_required', sa.String(length=50), nullable=False),
    sa.Column('plant_offered', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_offers_id'), 'marketplace_offers', ['id'], unique=False)
    op.create_index(op.f('ix_marketplace_offers_vendor_phone'), 'marketplace_offers', ['vendor_phone'], unique=False)
    op.alter_column('exchanges', 'vendor_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exchanges', 'vendor_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'nursery'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_marketplace_offers_vendor_phone'), table_name='marketplace_offers')
    op.drop_index(op.f('ix_marketplace_offers_id'), table_name='marketplace_offers')
    op.drop_table('marketplace_offers')
    # ### end Alembic commands ###
