"""Add acknowledged fields to alert_events

Revision ID: 5401e664bdcf
Revises: b0ef5d281f23
Create Date: 2026-06-20 12:04:36.783293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5401e664bdcf'
down_revision: Union[str, None] = 'b0ef5d281f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_events', sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('alert_events', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_events', 'acknowledged_at')
    op.drop_column('alert_events', 'acknowledged')
    # ### end Alembic commands ###
