"""fernet_device_secret_and_sensor_readings_hypertable

Revision ID: c609f5b32976
Revises: 58c6300519c4
Create Date: 2026-06-12 11:07:07.219209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c609f5b32976'
down_revision: Union[str, None] = '58c6300519c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of the sensor reading (hypertable partition key)'),
    sa.Column('device_id', sa.UUID(), nullable=False, comment='FK to devices.id'),
    sa.Column('temperature_c', sa.Double(), nullable=True, comment='Chamber temperature in °C'),
    sa.Column('humidity_pct', sa.Double(), nullable=True, comment='Relative humidity in %'),
    sa.Column('co2_ppm', sa.Double(), nullable=True, comment='CO₂ concentration in ppm'),
    sa.Column('ph_level', sa.Double(), nullable=True, comment='pH of composting material (0–14)'),
    sa.Column('ambient_temp_c', sa.Double(), nullable=True, comment='Ambient / external temperature in °C'),
    sa.Column('fan_speed_rpm', sa.Integer(), nullable=True, comment='Active fan speed in RPM'),
    sa.Column('fill_level_pct', sa.Double(), nullable=True, comment='Bin fill level from ultrasonic sensor in %'),
    sa.Column('weight_kg', sa.Double(), nullable=True, comment='Material weight in kg'),
    sa.Column('firmware_version', sa.String(length=50), nullable=True, comment='Firmware version at time of reading'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('time', 'device_id')
    )
    op.create_index('ix_sensor_readings_device_id_time', 'sensor_readings', ['device_id', 'time'], unique=False)

    # ── Convert to TimescaleDB hypertable ─────────────────────────────────────
    # Must be called BEFORE any data is inserted.
    # chunk_time_interval=86400000000 microseconds = 1 day.
    # if_not_exists=TRUE makes re-running migrations safe.
    op.execute(
        """
        SELECT create_hypertable(
            'sensor_readings',
            'time',
            chunk_time_interval => INTERVAL '1 day',
            if_not_exists => TRUE
        );
        """
    )

    op.add_column('devices', sa.Column('device_secret_enc', sa.Text(), nullable=False, server_default=''))
    op.drop_column('devices', 'device_secret_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_secret_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('devices', 'device_secret_enc')
    op.drop_index('ix_sensor_readings_device_id_time', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
