"""Add Exchange model

Revision ID: 8d17c4d4e663
Revises: 1398f2d1eeff
Create Date: 2026-07-11 17:39:16.422139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d17c4d4e663'
down_revision: Union[str, None] = '1398f2d1eeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor_phone', sa.String(length=20), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('compost_amount', sa.String(length=50), nullable=False),
    sa.Column('reward_type', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_id'), 'exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_exchanges_user_id'), 'exchanges', ['user_id'], unique=False)
    op.create_index(op.f('ix_exchanges_vendor_phone'), 'exchanges', ['vendor_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchanges_vendor_phone'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_user_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_id'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
