"""Add vendor_type to Exchange

Revision ID: 095e64076428
Revises: 8d17c4d4e663
Create Date: 2026-07-13 09:08:49.405948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095e64076428'
down_revision: Union[str, None] = '8d17c4d4e663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanges', sa.Column('vendor_type', sa.String(length=20), server_default='nursery', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchanges', 'vendor_type')
    # ### end Alembic commands ###
